# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI with Maven and Docker

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 20
          cache: maven
      - name: Set up Maven toolchain config
        shell: bash
        run: |
          mkdir -p $HOME/.m2 \
          && cat << EOF > $HOME/.m2/toolchains.xml
          <?xml version="1.0" encoding="UTF8"?>
          <toolchains>
            <toolchain>
              <type>jdk</type>
                <provides>
                  <version>20</version>
                  <vendor>adopt</vendor>
                </provides>
                <configuration>
                  <jdkHome>${{ env.JAVA_HOME }}</jdkHome>
                </configuration>
            </toolchain>
          </toolchains>
          EOF
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build with Docker
        run: docker build -t edwgiz.github.io/graalvm-helloworld .
